Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
m0=0.25
mf=0.05
dm=0.05
for dm in [0.05, 0.1, 0.15]:
    t = np.linspace(0,(m0-mf)/dm,500)
    dt=t[1]-t[0]

    sol = solve_ivp(lambda t, state:simplerocket(t, state, dmdt = dm), [0, t.max()], [0, 0, m0], t_eval=t)

    plt.plot(sol.t, sol.y[0], label = 'dm = {}'.format(dm))
plt.legend()
upload_imgur.upload_figure()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_2240/69557506.py[0m in [0;36m<module>[0;34m[0m
[1;32m     10[0m     [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0msol[0m[0;34m.[0m[0mt[0m[0;34m,[0m [0msol[0m[0;34m.[0m[0my[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0mlabel[0m [0;34m=[0m [0;34m'dm = {}'[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mdm[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     11[0m [0mplt[0m[0;34m.[0m[0mlegend[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 12[0;31m [0mupload_imgur[0m[0;34m.[0m[0mupload_figure[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'upload_imgur' is not defined
NameError: name 'upload_imgur' is not defined

